import type { ApprovalView, ArtifactView, RunDetail, TaskView } from "@/lib/types";

export function task(overrides: Partial<TaskView> = {}): TaskView {
  return {
    id: "core",
    title: "Implement the booking core with tests",
    specialist: "Backend specialist",
    deliverable: "booking.py and tests",
    acceptance_criteria: ["Double booking is refused"],
    status: "REVIEWING",
    state: "Validating",
    capability: "developer_sandbox",
    capability_label: "Sandboxed development",
    dependencies: [],
    attempt: 1,
    max_attempts: 3,
    revisions: 0,
    blocker: null,
    required_checks: [
      { check: "compile", label: "Python compile", status: "passed" },
      { check: "pytest", label: "Candidate tests", status: "not_run" },
    ],
    review_required: true,
    artifact_ids: ["a1"],
    latest_artifact_id: "a1",
    failure_count: 0,
    latest_event: null,
    usage: null,
    updated_at: "2026-09-27T10:00:00Z",
    ...overrides,
  };
}

export function artifact(overrides: Partial<ArtifactView> = {}): ArtifactView {
  return {
    id: "a1",
    task_id: "core",
    task_title: "Implement the booking core with tests",
    specialist: "Backend specialist",
    kind: "code_change",
    status: "candidate",
    version: 1,
    predecessor_id: null,
    input_artifact_ids: [],
    content_digest: "d".repeat(64),
    workspace_fingerprint: "f".repeat(64),
    workspace_id: "w1",
    integrated_commit: null,
    changed_files: ["booking.py"],
    validation_state: "partial",
    review_state: "not_reviewed",
    validations: [],
    reviews: [],
    summary: "Implemented",
    content_chars: 10,
    created_at: "2026-09-27T10:00:00Z",
    ...overrides,
  };
}

export function approval(overrides: Partial<ApprovalView> = {}): ApprovalView {
  return {
    id: "ap1",
    action: "publish_to_main",
    category: "candidate_action",
    title: "Approve: publish to main",
    what: "Allow Cavman to publish to main the accepted work.",
    why: "Publish the accepted booking core.",
    changes: ["Target: main"],
    risk: "Action affects canonical project state",
    target: "main",
    scope: { task_id: "core", target: "main" },
    scope_digest: "a".repeat(64),
    artifact_refs: ["a1"],
    required: true,
    status: "pending",
    created_at: "2026-09-27T10:00:00Z",
    decided_at: null,
    decision: null,
    ...overrides,
  };
}

export function runDetail(overrides: Partial<RunDetail> = {}): RunDetail {
  return {
    id: "r".repeat(32),
    project_id: "p".repeat(32),
    project_name: "Booking app",
    prompt: "Build me a booking app",
    executor: "provider",
    status: "completed",
    state: "complete",
    label: "Complete",
    explanation: "",
    stage: "deliver",
    task_counts: { Accepted: 1 },
    tasks_total: 1,
    tasks_accepted: 1,
    pending_approvals: 0,
    failures: 0,
    cost_usd: 0.1234,
    cost_complete: true,
    model_calls: 5,
    created_at: "2026-09-27T10:00:00Z",
    updated_at: "2026-09-27T10:05:00Z",
    objective: "Build me a booking app",
    constraints: [],
    criteria: ["Booking core implemented with passing sandboxed tests"],
    tasks: [task({ state: "Accepted", status: "ACCEPTED", required_checks: [{ check: "pytest", label: "Candidate tests", status: "passed" }] })],
    artifacts: [artifact({ status: "accepted" })],
    accepted_artifact_ids: ["a1"],
    approvals: [],
    capability_requests: [],
    failure_details: [],
    recovery: { revision: 0, replans_remaining: 3, proposals: [] },
    unresolved_issues: [],
    usage: {
      calls: 5,
      cost_usd: 0.1234,
      cost_complete: true,
      calls_without_cost: 0,
      tokens: { input_tokens: 100, output_tokens: 50, cached_tokens: 0, total_tokens: 150 },
      by_model: {},
      by_role: {},
      budget: { limit_usd: 5, spent_usd: 0.1234, remaining_usd: 4.8766, max_model_calls: 300, model_calls: 5, warning: false, exceeded: false },
    },
    jobs: [],
    event_cursor: 10,
    timeline: [],
    final_result: "Delivered.",
    delivery: null,
    ...overrides,
  };
}
